apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: prod
    app: frontend
    version: "1"
spec:
  containers:
  - name: nginx
    image: nginx
  nodeSelector:
    disktype: ssd
    
