apiVersion: v1
kind: Pod
metadata:
  name: memory-cpu
spec:
  containers:
  - name: memory-demo-ctr
    image: polinux/stress
    resources:
      limits:
        memory: "300Mi"
        cpu: "1"
      requests:
        cpu: "0.5"
        memory: "200Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]
